name = "zpa-zyrardow"
compatibility_date = "2025-08-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability]
enabled = true

[[assets.headers]]
for = "/assets/*"
[assets.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[assets.headers]]
for = "/sw.js"
[assets.headers.values]
Cache-Control = "no-cache"
